import type { Pool } from 'mysql2/promise';
import { AppError } from '../../errors.js';

export type BudgetTier = 'budget' | 'standard' | 'premium' | 'luxury';
export type MultiDayActivity = { id:number; title:string; summary:string; district:string; address:string; durationMinutes:number; budgetYuan:number; coverImageUri:string|null; tips:string[]|string; latitude?:number|null; longitude?:number|null; navigationUrl?:string|null };
export type SupportPoi = { id:number; name:string; kind:'restaurant'|'cafe'|'hotel'|'nightlife'; tier:BudgetTier; address:string; district:string; latitude:number; longitude:number; avgPriceYuan:number|null; sourceUrl:string|null };
type TripItem={type:'transport'|'activity'|'meal'|'hotel'|'nightlife';activityId:number|null;name:string;summary:string;timeSlot:'上午'|'中午'|'下午'|'晚上';startTime:string;durationMinutes:number;budgetYuan:number;district:string;address:string;coverImageUri:string|null;sourceUrl:string|null;transportNote:string|null;tips:string[]};
export type ComposedTrip={destinationCityId:number;destination:string;originName:string|null;daysCount:number;travelers:number;budgetTier:BudgetTier;totalBudgetEstimate:number;budgetBreakdown:{intercityTransport:number;hotel:number;meals:number;localTransport:number;activities:number;reserve:number};stayRecommendation:{name:string;address:string;tier:BudgetTier;estimatedNightlyPrice:number;sourceUrl:string|null;note:string}|null;summary:string;days:{day:number;theme:string;dailyBudgetEstimate:number;items:TripItem[]}[]};

function parseStringArray(value:string[]|string){if(Array.isArray(value))return value;try{const parsed=JSON.parse(value) as unknown;return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}}
function placeKey(item:MultiDayActivity){return `${item.district}:${item.address}`.replace(/\s+/g,'').toLowerCase()}
function tierRank(tier:BudgetTier){return {budget:0,standard:1,premium:2,luxury:3}[tier]}
function defaultPrice(kind:SupportPoi['kind'],tier:BudgetTier){const rank=tierRank(tier);if(kind==='hotel')return [220,420,760,1300][rank]!;if(kind==='restaurant')return [60,120,260,480][rank]!;if(kind==='cafe')return [35,55,90,150][rank]!;return [80,160,320,600][rank]!}
function distanceKm(a:{latitude?:number|null;longitude?:number|null},b:{latitude?:number|null;longitude?:number|null}){if(a.latitude==null||a.longitude==null||b.latitude==null||b.longitude==null)return Infinity;const rad=Math.PI/180;const dLat=(b.latitude-a.latitude)*rad;const dLon=(b.longitude-a.longitude)*rad;const h=Math.sin(dLat/2)**2+Math.cos(a.latitude*rad)*Math.cos(b.latitude*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.asin(Math.sqrt(h))}
function transportText(km:number){if(!Number.isFinite(km))return '建议使用地图确认实时路线';if(km<=1.5)return `步行约 ${Math.max(10,Math.round(km*15))} 分钟`;if(km<=8)return `建议地铁或网约车，约 ${Math.round(18+km*3)} 分钟`;return `建议地铁结合网约车，约 ${Math.round(25+km*3)} 分钟`}
function nearestPoi(candidates:SupportPoi[],target:{latitude?:number|null;longitude?:number|null},maxKm=8,excludedIds=new Set<number>()){const ranked=candidates.filter(item=>!excludedIds.has(item.id)).map(item=>({item,km:distanceKm(target,item)})).filter(result=>result.km<=maxKm).sort((a,b)=>a.km-b.km);return ranked[0]??null}
function centralHotel(candidates:SupportPoi[],places:MultiDayActivity[],tier:BudgetTier){const preferred=candidates.filter(item=>item.kind==='hotel'&&(tier==='luxury'?item.tier==='luxury'||item.tier==='premium':true));const pool=preferred.length?preferred:candidates.filter(item=>item.kind==='hotel');return pool.map(item=>({item,score:places.reduce((sum,place)=>sum+Math.min(30,distanceKm(place,item)),0)/Math.max(1,places.length)+Math.abs(tierRank(tier)-tierRank(item.tier))*4})).sort((a,b)=>a.score-b.score)[0]?.item??null}

export function composeTripFromActivities(input:{cityId:number;cityName:string;originName?:string|null;days:number;travelers:number;budget:number|null;budgetTier?:BudgetTier;mood:string;activities:MultiDayActivity[];supportPois?:SupportPoi[]}):ComposedTrip{
  const budgetTier=input.budgetTier??'standard';
  const unique=input.activities.filter((item,index,list)=>list.findIndex(candidate=>placeKey(candidate)===placeKey(item))===index);
  const required=input.days*2;
  if(unique.length<required)throw new AppError(422,'MULTI_DAY_CONTENT_INSUFFICIENT',`${input.cityName}目前只有 ${unique.length} 个可用核心地点，不足以生成每天两个地点的 ${input.days} 天详细行程。`,{requiredActivities:required,availableActivities:unique.length});
  const selected:MultiDayActivity[]=[];const remaining=[...unique];
  while(selected.length<required&&remaining.length){const anchor=remaining.shift()!;selected.push(anchor);if(selected.length>=required)break;const bestIndex=remaining.reduce((best,item,index)=>{const bestItem=remaining[best];const same=item.district===anchor.district;const bestSame=bestItem?.district===anchor.district;if(same&&!bestSame)return index;if(same===bestSame&&distanceKm(anchor,item)<distanceKm(anchor,bestItem??{}))return index;return best},0);selected.push(remaining.splice(bestIndex,1)[0]!)}

  const support=input.supportPois??[];const preferred=[...support].sort((a,b)=>Math.abs(tierRank(budgetTier)-tierRank(a.tier))-Math.abs(tierRank(budgetTier)-tierRank(b.tier)));
  const hotel=centralHotel(preferred,selected,budgetTier);const restaurants=preferred.filter(item=>item.kind==='restaurant');const cafes=preferred.filter(item=>item.kind==='cafe');const nightlife=preferred.filter(item=>item.kind==='nightlife');
  const rooms=Math.max(1,Math.ceil(input.travelers/2));const nights=Math.max(0,input.days-1);const hotelNight=hotel?(hotel.avgPriceYuan??defaultPrice('hotel',hotel.tier)):defaultPrice('hotel',budgetTier);const hotelBudget=hotelNight*nights*rooms;const intercity=input.originName&&input.originName.replace(/市$/,'')!==input.cityName.replace(/市$/,'')?400*input.travelers:0;const localTransport=60*input.travelers*input.days;const activityBudget=selected.reduce((sum,item)=>sum+item.budgetYuan*input.travelers,0);let mealBudget=0;let experienceBudget=0;const usedSupportIds=new Set<number>();
  const days=Array.from({length:input.days},(_,dayIndex)=>{const morning=selected[dayIndex*2]!;const afternoon=selected[dayIndex*2+1]!;const district=morning.district;const premiumRestaurants=restaurants.filter(item=>item.tier==='luxury'||item.tier==='premium');const mealPool=budgetTier==='luxury'&&premiumRestaurants.length?premiumRestaurants:restaurants;const lunchPick=nearestPoi(mealPool,morning,5,usedSupportIds);const lunch=lunchPick?.item??null;if(lunch)usedSupportIds.add(lunch.id);const dinnerPick=nearestPoi(mealPool,afternoon,6,usedSupportIds);const dinner=dinnerPick?.item??null;if(dinner)usedSupportIds.add(dinner.id);const eveningPool=input.mood==='热闹'&&nightlife.length?nightlife:[...nightlife,...cafes];const eveningTarget=dinner??afternoon;const eveningPick=nearestPoi(eveningPool,eveningTarget,5,usedSupportIds);const evening=eveningPick?.item??null;if(evening)usedSupportIds.add(evening.id);const lunchCost=(lunch?.avgPriceYuan??defaultPrice('restaurant',budgetTier))*input.travelers;const dinnerCost=(dinner?.avgPriceYuan??defaultPrice('restaurant',budgetTier))*input.travelers;const eveningCost=evening?(evening.avgPriceYuan??defaultPrice(evening.kind,budgetTier))*input.travelers:0;mealBudget+=lunchCost+dinnerCost;experienceBudget+=eveningCost;const moveKm=distanceKm(lunch??morning,afternoon);const items:TripItem[]=[
    {type:'activity',activityId:morning.id,name:morning.title,summary:morning.summary,timeSlot:'上午',startTime:'09:30',durationMinutes:morning.durationMinutes,budgetYuan:morning.budgetYuan*input.travelers,district:morning.district,address:morning.address,coverImageUri:morning.coverImageUri,sourceUrl:morning.navigationUrl??null,transportNote:dayIndex===0?'从住宿区域出发，提前查看实时路线':'从酒店或上一晚活动区域出发',tips:parseStringArray(morning.tips)},
    {type:'meal',activityId:null,name:lunch?.name??`在${district}选择当地餐厅`,summary:lunch?'高德地点库中的具体餐饮候选，出发前确认营业与订位。':'5公里内没有合适餐饮候选，保留为当前区域现场选择。',timeSlot:'中午',startTime:'12:30',durationMinutes:75,budgetYuan:lunchCost,district:lunch?.district??district,address:lunch?.address??district,coverImageUri:null,sourceUrl:lunch?.sourceUrl??null,transportNote:lunchPick?transportText(lunchPick.km):'不跨区推荐，抵达后在当前区域选择',tips:['轻奢档建议提前订位','价格以现场菜单为准']},
    {type:'activity',activityId:afternoon.id,name:afternoon.title,summary:afternoon.summary,timeSlot:'下午',startTime:'14:30',durationMinutes:afternoon.durationMinutes,budgetYuan:afternoon.budgetYuan*input.travelers,district:afternoon.district,address:afternoon.address,coverImageUri:afternoon.coverImageUri,sourceUrl:afternoon.navigationUrl??null,transportNote:transportText(moveKm),tips:parseStringArray(afternoon.tips)},
    {type:'meal',activityId:null,name:dinner?.name??`在${afternoon.district}安排晚餐`,summary:dinner?'晚餐候选与下午活动按经纬度就近组合。':'6公里内没有匹配档位的餐厅，保留为当前区域现场选择。',timeSlot:'晚上',startTime:'18:30',durationMinutes:90,budgetYuan:dinnerCost,district:dinner?.district??afternoon.district,address:dinner?.address??afternoon.district,coverImageUri:null,sourceUrl:dinner?.sourceUrl??null,transportNote:dinnerPick?transportText(dinnerPick.km):'不跨区推荐，留在下午活动区域用餐',tips:['确认营业时间与最低消费','多人出行建议提前订位']},
  ];if(evening&&eveningPick)items.push({type:evening.kind==='nightlife'?'nightlife':'meal',activityId:null,name:evening.name,summary:evening.kind==='nightlife'?'饭后5公里内的夜间体验候选，可根据当天体力决定是否前往。':'饭后5公里内的咖啡候选。',timeSlot:'晚上',startTime:'20:30',durationMinutes:90,budgetYuan:eveningCost,district:evening.district,address:evening.address,coverImageUri:null,sourceUrl:evening.sourceUrl,transportNote:`${transportText(eveningPick.km)}，结束后返回酒店`,tips:['确认营业时间','酒吧类场所请勿酒后驾车']});return{day:dayIndex+1,theme:dayIndex===0?`热闹开场 · ${district}`:dayIndex===input.days-1?'松弛收尾':`${input.mood}与城市体验`,dailyBudgetEstimate:items.reduce((sum,item)=>sum+item.budgetYuan,0)+60*input.travelers,items}});
  const subtotal=intercity+hotelBudget+mealBudget+experienceBudget+localTransport+activityBudget;const reserve=Math.round(subtotal*.1);const total=subtotal+reserve;
  if(input.budget!==null&&total>input.budget)throw new AppError(422,'TRIP_BUDGET_NOT_FEASIBLE',`当前总预算约 ¥${input.budget}，但这趟 ${input.days} 天行程的最低可执行估算约为 ¥${total}。建议提高预算、减少天数或改为本地游。`,{budget:input.budget,minimumEstimate:total});
  return{destinationCityId:input.cityId,destination:input.cityName,originName:input.originName??null,daysCount:input.days,travelers:input.travelers,budgetTier,totalBudgetEstimate:total,budgetBreakdown:{intercityTransport:intercity,hotel:hotelBudget,meals:mealBudget,localTransport,activities:activityBudget+experienceBudget,reserve},stayRecommendation:hotel?{name:hotel.name,address:hotel.address,tier:hotel.tier,estimatedNightlyPrice:hotelNight,sourceUrl:hotel.sourceUrl,note:`建议住在${hotel.district}，多人出行按 ${rooms} 间房估算；需确认房态与实时价格。`}:null,summary:`${input.cityName} ${input.days} 天详细行程：每天两个真实核心地点，配套具体餐饮/夜间候选、酒店区域、时间轴与预算拆分。`,days};
}

export class MultiDayComposerService{
  constructor(private pool:Pool){}
  async compose(input:{cityId:number;originName?:string|null;days:number;travelers:number;budget:number|null;budgetTier?:BudgetTier;mood:string}){
    const[cityRows]=await this.pool.execute('SELECT name FROM cities WHERE id=? AND is_active=TRUE LIMIT 1',[input.cityId]);const cityName=(cityRows as {name:string}[])[0]?.name;if(!cityName)throw new AppError(404,'CITY_NOT_FOUND','目的地城市不存在');
    const[rows]=await this.pool.execute(`SELECT id,title,summary,district,address,duration_minutes AS durationMinutes,budget_yuan AS budgetYuan,cover_image AS coverImageUri,tips,latitude,longitude,navigation_url AS navigationUrl FROM activities WHERE city_id=? AND is_active=TRUE AND content_status='published' AND content_score>=70 ORDER BY (mood=?) DESC,content_score DESC,id ASC LIMIT 60`,[input.cityId,input.mood]);
    const[supportRows]=await this.pool.execute(`SELECT id,name,kind,tier,address,district,latitude,longitude,avg_price_yuan AS avgPriceYuan,source_url AS sourceUrl FROM trip_support_pois WHERE city_id=? AND is_active=TRUE AND verification_status<>'rejected' ORDER BY FIELD(tier,'luxury','premium','standard','budget'),id LIMIT 100`,[input.cityId]);
    return composeTripFromActivities({...input,cityName,activities:(rows as Record<string,unknown>[]).map(row=>({id:Number(row.id),title:String(row.title),summary:String(row.summary),district:String(row.district),address:String(row.address),durationMinutes:Number(row.durationMinutes),budgetYuan:Number(row.budgetYuan),coverImageUri:typeof row.coverImageUri==='string'?row.coverImageUri:null,tips:row.tips as string[]|string,latitude:row.latitude===null?null:Number(row.latitude),longitude:row.longitude===null?null:Number(row.longitude),navigationUrl:typeof row.navigationUrl==='string'?row.navigationUrl:null})),supportPois:(supportRows as Record<string,unknown>[]).map(row=>({id:Number(row.id),name:String(row.name),kind:row.kind as SupportPoi['kind'],tier:row.tier as BudgetTier,address:String(row.address),district:String(row.district),latitude:Number(row.latitude),longitude:Number(row.longitude),avgPriceYuan:row.avgPriceYuan===null?null:Number(row.avgPriceYuan),sourceUrl:typeof row.sourceUrl==='string'?row.sourceUrl:null}))});
  }
}
