/** Shared visual rules for nearby and manually selected city plans. */
export function PlayConfigDesign() {
  return <style>{`
.pc-box-page{--play-bg:#0e1110;--play-surface:#111612;--play-input:#1a201b;--play-text:#f5f7ef;--play-muted:#a2ada0;--play-accent:#c9ff62;--play-border:rgba(220,235,208,.15);--play-radius:24px;background:radial-gradient(ellipse at 10% 0,rgba(156,191,79,.09),transparent 45%),var(--play-bg)!important}
.pc-box-page .pc-box-content{max-width:1120px;width:calc(100% - 48px);padding:28px 0 40px}
.pc-box-mode-picker{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:5px;border:1px solid var(--play-border);border-radius:18px;background:#111611;margin-bottom:24px}
.pc-box-mode-picker button{min-height:46px;border:0;border-radius:13px;background:transparent;color:var(--play-muted);font-size:14px;box-shadow:none}
.pc-box-mode-picker button[aria-pressed=true]{background:#28351c;color:var(--play-accent);box-shadow:inset 0 0 0 1px rgba(201,255,98,.4)}
.pc-box-page .nearby-short-plan,.pc-box-page .pc-box-sections{width:100%;max-width:none;margin:0;border:1px solid var(--play-border);border-radius:var(--play-radius);background:var(--play-surface);box-shadow:0 12px 32px rgba(0,0,0,.12);overflow:hidden}
.pc-box-page .nearby-short-plan{padding:28px}
.pc-box-page .nearby-short-plan header{padding-bottom:22px;margin-bottom:24px;border-bottom:1px solid var(--play-border)}
.pc-box-page .nearby-short-plan header small{font-size:12px;color:var(--play-accent);font-weight:750}
.pc-box-page .nearby-short-plan h2{font-size:26px;line-height:1.35;letter-spacing:-.025em;margin:10px 0}
.pc-box-page .nearby-short-plan header p,.pc-box-mode-help{font-size:14px;line-height:1.7;color:var(--play-muted)}
.pc-box-page .nearby-plan-field{margin:24px 0}.pc-box-page .nearby-plan-field legend,.pc-box-page .nearby-plan-numbers label,.pc-box-page .pc-box-label{font-size:14px;font-weight:700;color:#c9d2c3;margin-bottom:12px;letter-spacing:0}
.pc-box-page .nearby-plan-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}
.pc-box-page .nearby-plan-field-kind .nearby-plan-options{grid-template-columns:repeat(2,minmax(0,1fr))}
.pc-box-page .nearby-plan-options button,.pc-box-page .pc-box-options .ant-tag-checkable-group-item.ant-tag{display:flex;align-items:center;justify-content:center;gap:0;min-height:48px;padding:10px 12px;border:1px solid var(--play-border)!important;border-radius:999px!important;background:var(--play-input)!important;color:#bcc6b6;font-size:14px;font-weight:650;line-height:1.4;box-shadow:none!important;white-space:normal;transition:background .18s,border-color .18s}
.pc-box-page .nearby-plan-options button[aria-pressed=true],.pc-box-page .pc-box-options .ant-tag-checkable-group-item.ant-tag-checkable-checked{background:#26321e!important;border-color:var(--play-accent)!important;color:#e0ffae;box-shadow:none!important}
.pc-box-page .nearby-plan-options button[aria-pressed=true]::before,.pc-box-page .pc-box-options .ant-tag-checkable-group-item.ant-tag-checkable-checked::before{content:'';width:6px;height:6px;flex:none;margin-right:8px;border-radius:50%;background:var(--play-accent);box-shadow:none}
.pc-box-page .nearby-plan-numbers{gap:12px}.pc-box-page .nearby-plan-numbers input,.pc-box-page .nearby-plan-numbers select{min-height:50px;border-color:var(--play-border);border-radius:14px;background:var(--play-input);font-weight:700}
.pc-box-page .nearby-plan-consent{padding:14px;border:1px solid var(--play-border);border-radius:14px;background:#161d16;color:var(--play-muted)}
.pc-box-page .nearby-plan-consent input{accent-color:var(--play-accent)}
.pc-box-page .nearby-plan-generate,.pc-box-page .pc-box-start-button.ant-btn{min-height:52px;border-radius:999px!important;background:var(--play-accent)!important;color:#1a2312!important;font-size:16px!important;font-weight:800!important;box-shadow:none!important}
.pc-box-page .pc-box-section .ant-card-body{padding:26px 28px}.pc-box-page .pc-box-section-heading{gap:12px;margin-bottom:24px}.pc-box-page .pc-box-section-icon{width:38px;height:38px;border-radius:12px;color:var(--play-accent);background:#202a18;border:1px solid rgba(201,255,98,.25)}
.pc-box-page .pc-box-section-title{font-size:20px;color:var(--play-text)}
.pc-box-page .pc-box-city-select.ant-select{height:52px}.pc-box-page .pc-box-city-select .ant-select-content{background:var(--play-input);border-radius:14px}
.pc-box-page .pc-box-workbench{gap:20px;align-items:start}.pc-box-page .pc-box-visual{min-height:0;border-color:var(--play-border);border-radius:var(--play-radius);box-shadow:none;align-self:start}.pc-box-page .pc-box-visual-image{height:230px;min-height:0;flex:none}.pc-box-page .pc-box-visual-city strong{font-size:44px}.pc-box-page .pc-box-visual-copy{padding:20px}.pc-box-page .pc-box-visual-copy h2{font-size:22px}
.pc-box-page .pc-box-action{position:relative;inset:auto;z-index:1;margin-top:20px;padding:18px;border-radius:var(--play-radius);border-color:var(--play-border);background:var(--play-surface);box-shadow:none;backdrop-filter:none;display:flex;gap:16px;align-items:center}.pc-box-page .pc-box-summary-value{font-size:13px;font-weight:600;color:var(--play-muted)!important;white-space:normal}
.pc-box-page .nearby-plan-result{background:#111811;border-color:var(--play-border);border-radius:20px}.pc-box-page .nearby-plan-actions button,.pc-box-page .nearby-plan-actions a{border-radius:999px;min-height:44px}
@media(max-width:760px){.pc-box-page .pc-box-content{width:calc(100% - 32px);padding:20px 0 32px}.pc-box-mode-picker{margin-bottom:18px}.pc-box-mode-picker button{font-size:13px;padding:10px 6px}.pc-box-page .nearby-short-plan{padding:20px}.pc-box-page .nearby-short-plan h2{font-size:23px}.pc-box-page .nearby-short-plan header{padding-bottom:18px;margin-bottom:20px}.pc-box-page .nearby-plan-field{margin:22px 0}.pc-box-page .pc-box-section .ant-card-body{padding:24px 20px}.pc-box-page .pc-box-section-title{font-size:19px}.pc-box-page .pc-box-options.ant-tag-checkable-group{grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.pc-box-page .pc-box-group-category .pc-box-options.ant-tag-checkable-group{grid-template-columns:repeat(2,minmax(0,1fr))}.pc-box-page .pc-box-action{flex-direction:column;align-items:stretch;padding:18px 20px}.pc-box-page .pc-box-action-buttons,.pc-box-page .pc-box-action-buttons .ant-space-item,.pc-box-page .pc-box-start-button{width:100%}.pc-box-page .pc-box-visual{order:0}.pc-box-page .pc-box-visual-copy,.pc-box-page .pc-box-visual-signals,.pc-box-page .pc-box-visual-range{display:none}.pc-box-page .pc-box-visual-image{height:180px}.pc-box-page .pc-box-visual-city strong{font-size:38px}.pc-box-page .pc-box-group-surprise .pc-box-options.ant-tag-checkable-group{grid-template-columns:1fr}.pc-box-page .pc-box-group-surprise .ant-tag-checkable-group-item.ant-tag-checkable-checked::before{display:none}}
@media(prefers-reduced-motion:reduce){.pc-box-page button,.pc-box-page .ant-tag{transition:none!important}}
`}</style>;
}
