-- 仅用于本地开发环境。生产环境请使用独立密钥管理和最小权限账号。
CREATE DATABASE IF NOT EXISTS lazyde
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'lazyde_app'@'127.0.0.1'
  IDENTIFIED BY 'lazyde_dev_2026';
CREATE USER IF NOT EXISTS 'lazyde_app'@'localhost'
  IDENTIFIED BY 'lazyde_dev_2026';
CREATE USER IF NOT EXISTS 'lazyde_app'@'%'
  IDENTIFIED BY 'lazyde_dev_2026';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE TEMPORARY TABLES, ALTER, INDEX, REFERENCES
  ON lazyde.* TO 'lazyde_app'@'127.0.0.1';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE TEMPORARY TABLES, ALTER, INDEX, REFERENCES
  ON lazyde.* TO 'lazyde_app'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE TEMPORARY TABLES, ALTER, INDEX, REFERENCES
  ON lazyde.* TO 'lazyde_app'@'%';

FLUSH PRIVILEGES;
