CREATE TABLE IF NOT EXISTS trip_support_pois (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  city_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  kind ENUM('restaurant','cafe','hotel','nightlife') NOT NULL,
  tier ENUM('budget','standard','premium','luxury') NOT NULL DEFAULT 'standard',
  address VARCHAR(255) NOT NULL,
  district VARCHAR(80) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  avg_price_yuan SMALLINT UNSIGNED NULL,
  tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
  cover_image VARCHAR(500) NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'amap',
  source_url VARCHAR(500) NULL,
  verification_status ENUM('unverified','source_checked','verified','rejected') NOT NULL DEFAULT 'source_checked',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_trip_support_city_kind_name (city_id, kind, name),
  KEY idx_trip_support_match (city_id, kind, tier, is_active),
  CONSTRAINT fk_trip_support_city FOREIGN KEY (city_id) REFERENCES cities(id)
) ENGINE=InnoDB;
