CREATE TABLE IF NOT EXISTS trip_execution_progress (
  todo_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  active_step INT UNSIGNED NOT NULL DEFAULT 0,
  paused BOOLEAN NOT NULL DEFAULT FALSE,
  skipped JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
